name: Tests
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make
        make examples

    - name: Test
      run: |
        ./bin/example-basic share/data/IGRF13.COF
        ./bin/example-basic share/data/WMM2020.COF

  OSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make
        make examples

    - name: Test
      run: ./bin/example-basic
